name: ci-backend-workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  pull_request:
    branches: 
      - main
    paths:
      - 'starter/backend/**'

#Use a matrix strategy
jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8.x, 3.10.x]

    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v3

      # Set up a Python environment using the specified node version.
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install the dependencies.
      - name: Install the dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv shell
      - name: pipenv install
        run:  cd starter/backend && pipenv install
      # Run lint
      - name: Run lint
        run: cd starter/backend && pipenv run lint
      # Run the tests.
      - name: Run test
        run: cd starter/backend && pipenv run test

  build:
    needs: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8.x, 3.10.x]

    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v3

      # Set up a Python environment using the specified node version.
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install the dependencies.
      - name: Install the dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          cd starter/backend && pipenv install
      # Docker build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Docker build
        run: docker build -t my-backend-app:${{ github.sha }} ./starter/backend

      # Send a console message at completion.
      - run: |
          echo "Hello ${{github.actor}}. You pull to ${{github.repository}} at $(date)."

        