name: cd-backend-workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  pull_request:
    branches: 
      - main
    paths:
      - 'starter/backend/**'
    types: [closed]
env:
  GITHUB_SHA: ${{ github.sha }}
jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy: 
      matrix:
        python-version: [3.10.x]

    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v3

      # Set up a Node.js environment using the specified node version.
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install the dependencies.
      - name: Install the dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          echo "haha ${{secrets.AWS_ACCESS_KEY_ID}}"
      
      # - name: pipenv shell
      #   run: pipenv shell
      - name: pipenv i
        run: cd starter/backend && pipenv install

      # Run the tests.
      - name: Run test
        run: cd starter/backend && pipenv run test

  deploy:
    needs: build-test
    environment:
      name: staging
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v3
      # deploy
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: us-east-1
        env:
          kaka: haha
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Get ECR login password
        id: ecr-login
        run: |
          echo "::set-output name=password::$(aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }})"

      # - name: Login to container registry
        # uses: docker/login-action@v2
        # with:
        #   registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com
        #   username: ${{ secrets.REGISTRY_USERNAME }}
        #   password: ${{ steps.ecr-login.outputs.password }}
          # password: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      - name: Login to Amazon ECR
        id: login-ecr
        # uses: aws-actions/amazon-ecr-login@v1
        run: aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: ./starter/backend/Dockerfile
      #     push: true
      #     tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/backend:${{env.GITHUB_SHA}}
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{secrets.AWS_DEFAULT_REGION}}.amazonaws.com
          IMAGE_TAG: ${{ env.GITHUB_SHA }}
          IMAGE_REPO_NAME: backend
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          cd starter/backend && docker build -t $ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG .
          # docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
          docker push $ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Verify kubectl version
        run: kubectl version --client

      - name: Install kustomize
        run: |
          wget -O /tmp/kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.4.0/kustomize_v4.4.0_linux_amd64.tar.gz
          tar xzf /tmp/kustomize.tar.gz -C /tmp
          sudo mv /tmp/kustomize /usr/local/bin/kustomize
          sudo chmod +x /usr/local/bin/kustomize
          kustomize version
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name your-cluster-name --region your-region

      - name: Deploy to Kubernetes
        run: |
          cd starter/backend/k8s
          # aws eks update-kubeconfig --name your-cluster-name --region your-region
          kustomize edit set image backend=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/backend:${{env.GITHUB_SHA}}
          kustomize build | kubectl apply --validate=false --openapi-patch=false -f -
      - name: Get Service URL
        id: get-service-url
        run: |
          SERVICE_URL=$(kubectl get service -l app=backend -o=jsonpath='{.items[0].status.loadBalancer.ingress[0].hostname}')
          echo "::set-output name=service_url::$SERVICE_URL"
        continue-on-error: true

      - name: Output Service URL
        if: steps.get-service-url.outputs.service_url != ''
        run: echo "BACKEND_SERVICE_URL=${{ steps.get-service-url.outputs.service_url }}" >> $GITHUB_ENV
              